### ISSUE TITLE
HOOK-ERROR in before_all: AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by maryumnoor** [Virtualstock/behave-testrail-reporter#22]
Hi, 

Reaching out if you are familiar with this error. 

We are erroring out on this line :
`testrail_reporter = TestrailReporter(u'develop')`

with error:
`HOOK-ERROR in before_all: AttributeError: 'str' object has no attribute 'get'`

********************************************************
The changes we have added as per the document were in environment.py and testrail.yml as shared below

**environment.py**

```
def before_all(context):
....
    testrail_reporter = TestrailReporter(u'develop')
    context.config.reporters.append(testrail_reporter)
....
```

**testrail.yml** file with
  `      allowed_branch_pattern: '*'`

Not sure if we are missing anything that is causing this error. Please let us know if you know of a quick fix for this issue.

Thank you

**Comment by BernardoSilva** [comment]
Hi @maryumnoor ,

I actually found that issue when I was adding the last tests.

It can be fixed by adding a valid regex expression.

In your **testrail.yml**:

```
allowed_branch_pattern: '.*'
```

this should fix the problem, let us know if it worked out.

I will add that example to README to make clear how to allow any branch, created https://github.com/Virtualstock/behave-testrail-reporter/issues/23

**Comment by maryumnoor** [comment]
Hi, Thank you for your reply! 
But unfortunately, even that change continues to give the same error.

**Comment by BernardoSilva** [comment]
Hi @maryumnoor ,

How are you?

Sorry for not being able to spot the problem before.
The error you are experiencing is caused by an invalid configuration file.

Can you have a look into [this PR](https://github.com/Virtualstock/behave-testrail-reporter/pull/93) where I was able to reproduce the problem and maybe you can compare with your configuration?

Can you let me know if this was your problem? :) 

Cheers
